/** Korean UI copy and its reviewed English equivalent. User content is not translated. */
export const englishText: Record<string, string> = {
  // Navigation and account
  "홈": "Home",
  "수행평가": "Assignments",
  "발표연습": "Practice",
  "공부": "Study",
  "프로필": "Profile",
  "설정": "Settings",
  "오늘 급식": "Today's meals",
  "이번 주 급식": "Weekly meals",
  "학교 설정": "School settings",
  "꼬르륵": "Meals",
  "뒤로가기": "Back",
  "돌아가기": "Go back",
  "취소": "Cancel",
  "취소 및 닫기": "Cancel and close",
  "닫기": "Close",
  "확인": "OK",
  "확인 및 동의": "Confirm and agree",
  "다시 시도": "Try again",
  "다시 시작하기": "Start over",
  "저장": "Save",
  "저장하기": "Save",
  "등록": "Add",
  "등록하기": "Add",
  "수정": "Edit",
  "삭제": "Delete",
  "삭제하기": "Delete",
  "지우기": "Clear",
  "숨기기": "Hide",
  "불러오기": "Load",
  "선택": "Select",
  "선택하기": "Choose",
  "변경하기": "Change",
  "이메일": "Email",
  "비밀번호 (6자 이상)": "Password (at least 6 characters)",
  "비밀번호를 잊으셨나요?": "Forgot your password?",
  "이메일로 계속하기": "Continue with email",
  "Google 로그인": "Sign in with Google",
  "또는": "or",
  "처음이면 자동으로 회원가입, 이미 계정이 있으면 로그인됩니다": "New users are signed up automatically; existing users are signed in.",
  "스마트 스쿨메이트": "Your smart school companion",
  "수행평가 일정 관리와 급식 정보 조회를 한 번에 해결하는 1등급 학업 플랫폼": "Plan assignments and check school meals in one place.",
  "다른 계정으로 로그인": "Sign in with another account",
  "로그아웃": "Sign out",
  "로그인 계정": "Signed-in account",
  "이메일 인증이 필요해요": "Verify your email",
  "인증 확인하고 계속하기": "Check verification and continue",
  "주소로 인증 메일을 보냈어요. 메일함(스팸함 포함)에서 링크를 눌러 인증을 완료해 주세요.": "We sent a verification email. Open the link in your inbox or spam folder.",
  "문제가 발생했습니다": "Something went wrong",
  "예상치 못한 오류로 화면을 표시할 수 없습니다. 아래 버튼을 눌러 다시 시도해 주세요.": "An unexpected error prevented this screen from loading. Please try again.",
  // Subscription
  "요금제": "Plan",
  "현재 플랜": "Current plan",
  "일반": "Free",
  "똑 PRO": "TTOK PRO",
  "똑 PRO 구독": "TTOK PRO subscription",
  "똑 PRO 구독하기": "Subscribe to TTOK PRO",
  "구독 관리 / 해지": "Manage or cancel subscription",
  "구매 내역 복원": "Restore purchases",
  "이번 달 AI 사용량": "AI usage this month",
  "월 AI 사용량": "Monthly AI uses",
  "AI 추천 기능": "AI recommendations",
  "항목": "Feature",
  "연간 구독": "Yearly subscription",
  "월간 구독": "Monthly subscription",
  "현재 구매할 수 없어요": "Currently unavailable",
  // Home
  "안녕하세요,": "Hello,",
  "님!": "!",
  "오늘의 학습 성취": "Today's progress",
  "자주 쓰는 기능": "Quick access",
  "오늘 스케줄 라인": "Today's schedule",
  "오늘 등록된 스케줄이 없습니다.": "No tasks scheduled for today.",
  "위의 '+' 버튼을 클릭해 스케줄을 추가해 보세요!": "Tap + to add a task.",
  "등록된 다가오는 일정이 없습니다. 일정을 추가해 보세요!": "No upcoming events. Add one to get started.",
  "이번 학기 학습 목표": "This semester's goals",
  "등록된 학습 목표가 없습니다. 이번 학기를 빛낼 목표를 세워보세요!": "No goals yet. Set one for this semester.",
  "목표 저장": "Save goal",
  "목표 삭제": "Delete goal",
  "현재 목표": "Current goal",
  "원하는 학습목표를 자유롭게 직접 입력해 주세요 (예: 하루 1시간 독서하기)": "Enter a learning goal (for example, read for an hour each day).",
  "스케줄 추가": "Add task",
  "스케줄 제목": "Task title",
  "스케줄 제목 (예: 영어 숙제하기)": "Task title (e.g. English homework)",
  "시간 (예: 오후 4:00)": "Time (e.g. 4:00 PM)",
  "캘린더 일정 등록": "Add calendar event",
  "일정 등록하기": "Add event",
  "일정 수정": "Edit event",
  "일정 수정하기": "Edit event",
  "일정 삭제": "Delete event",
  "일정을 삭제하시겠습니까? 이 작업은 절대 복구할 수 없습니다.": "Delete this event? You cannot undo this action.",
  "AI 리포트": "AI report",
  "AI 데일리 학습 추천 제안": "Daily AI study suggestions",
  "지금 뭘 하면 좋을지 물어보기": "Ask what to study next",
  "할 일과 일정을 살펴보고 있어요...": "Reviewing your tasks and schedule...",
  "다시 스캔": "Scan again",
  // Assignment planning
  "수행평가 일정 관리": "Assignment planner",
  "수행평가 & 시험 카운트다운": "Assignments & exam countdown",
  "수행평가 직접 입력": "Enter assignment manually",
  "새 지필평가 일정 등록": "Add written exam",
  "등록된 수행평가 일정 없음": "No assignments yet",
  "등록된 지필평가 정보가 없습니다. 왼쪽 폼에서 시험을 먼저 추가해 주세요.": "No written exams yet. Add one using the form.",
  "등록된 지필평가 캘린더": "Written exam calendar",
  "수행평가 과제명": "Assignment title",
  "수행평가 제목": "Assignment title",
  "수행평가 제출일 예고 알림": "Assignment due date reminder",
  "수행평가 제출 하루 전 리마인드 알림 발송.": "Send a reminder one day before an assignment is due.",
  "수행평가 일정 수정": "Edit assignment",
  "수행평가 일정 삭제": "Delete assignment",
  "시험 과목": "Exam subject",
  "시험 평가명": "Exam name",
  "시험 출제 범위 (학습용)": "Exam topics (for studying)",
  "지필평가 / 시험 일정 알림": "Written exam reminders",
  "지필평가 일정 수정": "Edit written exam",
  "지필평가 일정 삭제": "Delete written exam",
  "지필 수행 계획": "Written exam plan",
  "최종 제출일": "Due date",
  "최종 제출일 및 평가일": "Due or assessment date",
  "제출 마감일 (자동 알림 생성)": "Due date (automatic reminder)",
  "제출 및 진행 방식": "Submission and presentation format",
  "제출 방법": "Submission method",
  "지참 준비물": "Items to bring",
  "필수 준비물": "Required materials",
  "평가 기준 (선택)": "Grading criteria (optional)",
  "평가 날짜": "Assessment date",
  "과목": "Subject",
  "과목명": "Subject name",
  "과목 (예: 영어)": "Subject (e.g. English)",
  "교과 과목": "School subject",
  "사진 등록": "Upload photo",
  "사진 선택": "Choose photo",
  "사진 촬영": "Take photo",
  "촬영": "Capture",
  "계획서 사진 선택하기": "Choose a plan photo",
  "또는 여기를 클릭해 카메라로 촬영": "Or tap here to take a photo",
  "텍스트 직접 입력": "Enter text manually",
  "이미지/계획서 등록": "Upload image or plan",
  "AI 사진 스캔 등록": "Scan a photo with AI",
  "AI 이미지 분석 중...": "AI is analyzing the image...",
  "AI 분석 중...": "AI is analyzing...",
  "AI 자동 정보 추출 결과": "AI extracted information",
  "분석된 평가 및 채점 기준": "Grading criteria and evaluation",
  "네트워크 상태가 원활한지 확인하고 글씨가 선명한 계획서 사진으로 다시 시도해 주세요.": "Check your connection and retry with a clear photo of the plan.",
  "캘린더 및 알림 자동 등록 완료": "Calendar event and reminder added",
  "직접 입력": "Enter manually",
  "등록 버튼 클릭 시,": "When you tap Add,",
  "이 똑 소리나게 자동 예약됩니다!": "will be scheduled automatically!",
  // Study
  "공부 기능 선택": "Choose a study tool",
  "AI 공부 도우미": "AI study assistant",
  "AI 공부 및 수험 전략": "AI study and exam strategy",
  "AI 요약": "AI summary",
  "AI 문제생성": "AI quiz generation",
  "AI 오답노트": "AI mistake notebook",
  "AI 질문하기": "Ask AI",
  "교과서 사진 등록": "Upload a textbook photo",
  "교과서 내용 직접 타이핑 (선택)": "Type textbook content (optional)",
  "교과서 핵심 요약화": "Summarize key ideas",
  "이미지가 없는 경우, 공부할 본문 내용을 직접 적어주세요...": "If you have no image, type the text you want to study...",
  "학습 분석 결과가 여기에 표시됩니다": "Your study results will appear here",
  "정답 채점 및 해설 보기": "Check answers and explanations",
  "문제를 다 푸셨나요? 정답 자가진단": "Finished the quiz? Check your answers.",
  "첫 번째 고사 대상: AI 공부 계획 생성하기": "Generate an AI study plan for your next exam",
  "지필고사 범위 맞춤형 공부 계획 생성 중...": "Creating a study plan for your exam topics...",
  "선생님에게 물어볼 구체적인 질문": "Specific questions for your teacher",
  "과외쌤 일대일 상담": "One-on-one tutoring",
  "클리닉 핵심 처방": "Key study recommendations",
  "핵심 태그 키워드": "Key topics",
  "학업 달성 게이지": "Learning progress",
  "시간 정보": "Time details",
  "실시간 계산": "Live calculation",
  "3단 자가진단 평가": "Three-step self-check",
  // Meals
  "급식 달력": "Meal calendar",
  "식단": "Menu",
  "영양정보": "Nutrition",
  "원산지 정보": "Ingredient origin",
  "등록된 급식이 없습니다.": "No school meal is available.",
  "주말, 공휴일, 방학 기간 중이거나 급식 계획이 없는 일정입니다.": "There may be no meal on weekends, holidays or during vacation.",
  "급식 업데이트 중...": "Updating meal information...",
  "전국 NEIS 서버에서 주간 급식 계획 수집 중...": "Loading this week's meals from NEIS...",
  "NEIS 오픈 API 연동 급식 정보 수집 중...": "Loading school meal information...",
  "급식 알림 설정": "Meal notifications",
  "급식 알림 시간 설정": "Meal notification time",
  "급식 알림 설정이 안전하게 동기화되었습니다!": "Meal notification settings saved!",
  "매일 맛있는 급식 메뉴 알림": "Daily meal notifications",
  "매일 맛있는 급식 알림": "Daily school meal alerts",
  "알림 꺼짐": "Notifications off",
  "알림 발송 예정 시간:": "Notification time:",
  "지정된 시간에 오늘의 급식 메뉴와 칼로리 알림 발송.": "Send today's meal and calorie information at the chosen time.",
  "지정된 시간에 오늘의 급식 메뉴와 칼로리 정보를 스마트 알림으로 전송합니다.": "Notify you of today's menu and calorie information at the chosen time.",
  "학교명 또는 지역명을 입력하세요 (예: 서울고, 부산)": "Enter a school or location (e.g. Seoul High School)",
  "학교 이름을 검색해 주세요 (예: 서울고)": "Search for a school (e.g. Seoul High School)",
  "대한민국 전국 초·중·고교 검색": "Search elementary, middle and high schools in Korea",
  "최근 검색 기록": "Recent searches",
  "최근에 검색한 학교 목록이 없습니다.": "No recently searched schools.",
  "검색 중...": "Searching...",
  "검색 결과가 없습니다.": "No results found.",
  "등록된 학교 정보가 없습니다": "No school selected",
  "상단의 \"학교 설정\" 탭으로 이동해 본인의 학교를 검색하고 등록해 보세요!": "Go to School settings to find and select your school.",
  "이번 주": "This week",
  "다음 주": "Next week",
  "이전 주": "Previous week",
  "다음 달": "Next month",
  "이전 달": "Previous month",
  // Profile
  "학생 프로필 관리": "Student profile",
  "학생 본명": "Student name",
  "소속 학교명": "School",
  "소속 반 (학급)": "Class",
  "학년": "Grade",
  "학년 수준": "Grade level",
  "학기 최종 목표": "Semester goal",
  "똑 부러지게 프로필 수정 완료": "Save profile changes",
  "수행평가 및 학습 프로필 갱신 완료!": "Profile updated!",
  "터치하여 키보드 이모지를 입력해 주세요 (예: 🐰🦁)": "Tap to enter an emoji (e.g. 🐰🦁)",
  "이모티콘 입력": "Enter an emoji",
  // Settings
  "설정 및 계정 관리": "Settings and account",
  "기기 연동 및 계정 관리": "Device sync and account",
  "데이터 백업 연동": "Cloud backup",
  "테마 설정": "Appearance",
  "다크 모드": "Dark mode",
  "라이트 모드": "Light mode",
  "라이트 모드와 다크 모드를 자유롭게 변환하세요.": "Switch between light and dark mode.",
  "화면 모드 변경": "Change appearance",
  "알림 설정": "Notification settings",
  "알림 규칙 적용 저장": "Save reminder settings",
  "데이터 전체 초기화": "Reset all data",
  "데이터 영구 삭제": "Permanently delete data",
  "주의 구역 (Danger Zone)": "Danger zone",
  "초기화 실행": "Reset data",
  "정말로 모든 수행평가 일정, 발표 연습 대본, 공부 기록을 초기화하시겠습니까?": "Reset all assignments, practice scripts and study records?",
  "이 작업은 되돌릴 수 없습니다.": "This action cannot be undone.",
  "지난 일정 자동 삭제": "Automatically delete old events",
  "일정을 적어둔 날에서 하루가 지나면 캘린더 및 리스트에서 자동으로 일정을 영구 삭제합니다.": "Delete events from the calendar and list one day after their date.",
  "서비스 이용약관": "Terms of service",
  "약관 내용 보기": "Read the terms",
  "똑(TTOK) 서비스 이용약관": "TTOK terms of service",
  "똑 (TTOK)의 정밀한 인공지능 분석 가이드 및 프라이버시 보호 약관을 확인합니다.": "Read TTOK's AI analysis and privacy terms.",
  "최종 개정일: 2026년 9월 12일": "Last revised: September 12, 2026",
  "제 1 조 (목적)": "Article 1 (Purpose)",
  "제 2 조 (용어의 정의)": "Article 2 (Definitions)",
  "제 3 조 (회원정보의 보호 및 개인정보 보안)": "Article 3 (Account and data protection)",
  "제 4 조 (이용자의 권리와 의무)": "Article 4 (User rights and obligations)",
  "제 5 조 (제공 서비스의 제한 및 면책조항)": "Article 5 (Service limits and disclaimer)",
  "제 6 조 (똑 PRO 유료 구독 및 결제)": "Article 6 (TTOK PRO subscription and payment)",
  "제 7 조 (지적재산권)": "Article 7 (Intellectual property)",
  "제 8 조 (계정 해지 및 이용 제한)": "Article 8 (Account termination)",
  "제 9 조 (약관의 변경)": "Article 9 (Changes to the terms)",
  "제 10 조 (준거법 및 관할법원)": "Article 10 (Governing law)",
  // Presentation practice
  "발표 연습 및 피드백": "Presentation practice and feedback",
  "발표 대본 작성": "Write a presentation script",
  "발표 연습 도와주기": "Practice your presentation",
  "나의 말하기 자세와 시선 처리를 똑똑하게 AI 교정 및 분석받으세요": "Get AI feedback on your speaking, posture and eye contact.",
  "발표 연습 시작하기": "Start practice",
  "발표 연습 중": "Practicing",
  "연습 종료 및 AI 종합 분석": "Finish and get AI feedback",
  "다시 연습하기": "Practice again",
  "분석 다시 시도": "Retry analysis",
  "분석을 완료하지 못했어요": "We couldn't finish the analysis",
  "분석에 실패했습니다": "Analysis failed",
  "똑(Tok) AI 발표 분석 중...": "TTOK AI is analyzing your presentation...",
  "실제 녹화한 영상과 음성을 바탕으로 말하기와 시선·자세를 분석하고 있습니다.": "Analyzing your speaking, eye contact and posture from the recording.",
  "관찰 근거를 확인한 뒤 평가 결과를 표시합니다.": "Results will be based on what can actually be observed.",
  "발표 6대 요소 평가": "Six presentation skills",
  "시선, 목소리, 발음, 자세, 제스처, 표정의 균형도입니다.": "Eye contact, voice, pronunciation, posture, gestures and expression.",
  "시선 처리": "Eye contact",
  "말의 속도": "Speaking pace",
  "선명한 발음": "Clear pronunciation",
  "바른 자세": "Posture",
  "제스처/손짓": "Gestures",
  "안면 표정": "Facial expression",
  "안정적 쉼표": "Natural pauses",
  "불필요 단어 수": "Filler words",
  "🎙️ 음성 종합 분석": "🎙️ Voice analysis",
  "👁️ 시각 태도 분석": "👁️ Visual delivery",
  "선생님의 핵심 발표 제언": "Key presentation advice",
  "똑똑 선생님의 구체적 피드백": "Detailed feedback",
  "발표 주제": "Presentation topic",
  "연습할 발표 주제": "Topic to practice",
  "연습할 대본 선택 및 입력": "Choose or enter a script",
  "희망 발표 시간": "Target presentation length",
  "희망 시간": "Target time",
  "발표 소요 시간": "Presentation length",
  "발표 목적": "Presentation goal",
  "대상 청중": "Audience",
  "원하는 말투": "Preferred tone",
  "발표 스타일": "Presentation style",
  "발표 상세 조건 입력": "Presentation details",
  "발표 아웃라인 구조": "Presentation outline",
  "스피치 본문 (제스처 훈련 포함)": "Script (including gesture cues)",
  "AI 완성 대본": "AI-generated script",
  "대본 생성하기": "Generate script",
  "대본 직접 수정": "Edit script",
  "대본 복사": "Copy script",
  "대본 공유": "Share script",
  "대본 삭제": "Delete script",
  "대본 프롬프터 켜기": "Open teleprompter",
  "대본이 리허설 프롬프터로 연동되었습니다!": "Script loaded into the teleprompter!",
  "이 대본을 보관함에 저장하기": "Save this script",
  "저장된 대본 목록": "Saved scripts",
  "📁 저장된 발표 대본 보관함": "📁 Saved presentation scripts",
  "아직 저장된 발표 대본이 없습니다.": "No saved presentation scripts yet.",
  "대본을 생성하거나 직접 입력하면 이곳에 자동으로 보관됩니다.": "Generated or entered scripts will appear here.",
  "작성된 대본이 여기에 생성됩니다": "Your script will appear here",
  "다른 곳에서 작성한 대본이나 직접 연습하고 싶은 대본 텍스트를 입력해 주세요...": "Paste a script you wrote elsewhere or enter one to practice...",
  "여기에 대본 내용을 붙여넣으세요": "Paste your script here",
  "발표 대본 프롬프터 (연습용)": "Presentation teleprompter",
  "PDF 저장": "Save PDF",
  "PDF 프린트/저장": "Print or save PDF",
  "작게": "Smaller",
  "크게": "Larger",
  "더크게": "Even larger",
  "크기": "Size",
  "🎲 랜덤 설정": "🎲 Random settings",
  "실시간 자막 (STT)": "Live captions (STT)",
  "연습 종료 시 녹화한 영상과 음성을 AI 분석 서버와 Google Gemini에 전송하는 데 동의합니다. 원본은 앱 서버에 저장되지 않습니다.": "I agree to send my recorded video and audio to the analysis server and Google Gemini when I finish practicing. The app server does not store the original recording.",
  "발표 영상을 기록하여 분석하기 위해 기기 카메라 권한이 꼭 필요합니다.": "Camera permission is needed to record and analyze your presentation.",
  "기기 권한 허용이 필요합니다": "Device permission required",
  "발표 분석을 위해 꼭 권한이 필요해요!": "Permission is needed for presentation analysis!",
  "카메라 권한 안내": "Camera permission help",
  "카메라 권한 요청": "Request camera permission",
  "카메라 권한 직접 허용하기": "Allow camera permission in settings",
  "카메라 켜기": "Turn on camera",
  "카메라 활성화 중...": "Starting camera...",
  "카메라 활성화 안내": "Camera setup help",
  "현재 카메라에 대한 접근이 차단되어 있어 AI 연습 모드를 시작할 수 없습니다.": "Camera access is blocked. Allow it to start practice mode.",
  "기기 다시 연결 및 권한 요청": "Reconnect device and request permission",
  "기기 다시 연결 및 권한 허용": "Reconnect device and allow permission",
  "기기를 찾을 수 없습니다": "Device not found",
  "다른 앱에서 기기를 사용 중입니다": "Another app is using the device",
  "미디어 접근 오류 발생": "Media access error",
  "보안 환경 제한 (HTTPS)": "Secure connection required (HTTPS)",
  "인앱 브라우저 제한:": "In-app browser limitation:",
  "앱별 기기 권한:": "App-specific permissions:",
  "확실한 해결 방법:": "How to fix this:",
  "[앱 설정 열기]": "[Open app settings]",
  "📱 안드로이드 앱 설정 열기": "📱 Open Android app settings",
  "📱 안드로이드 앱 사용자 추가 안내": "📱 More guidance for Android users",
  "📱 안드로이드 및 모바일 웹뷰 해결책:": "📱 Android and mobile WebView help:",
  "모바일 브라우저/인앱 웹뷰 보안 설정으로 인해 직접적인 미디어 스트림 수집이 제한될 수 있습니다.": "Mobile browsers and in-app WebViews may restrict camera and microphone access.",
  "카카오톡, 페이스북 등 앱 내부 브라우저는 하드웨어 카메라 권한을 차단할 가능성이 매우 높습니다.": "In-app browsers such as KakaoTalk and Facebook may block camera access.",
  "웹 브라우저 혹은 앱 설정에서 카메라 사용이 차단되었습니다. 주소창 옆의 권한 설정을 변경해 주세요.": "Camera access is blocked in your browser or app settings. Check the permission settings.",
  "카메라 기능은 보안 연결(HTTPS) 또는 로컬 환경에서만 브라우저 보안 규정상 허용됩니다. 안전한 접속 상태인지 확인해 주세요.": "Browsers allow camera access only on HTTPS or local pages. Check your connection.",
  "카메라를 줌(Zoom), 카카오톡, 또는 다른 브라우저 탭에서 사용 중일 수 있습니다. 해당 앱들을 완전히 종료한 후 새로고침해 주세요.": "Another app or browser tab may be using the camera. Close it and try again.",
  "사용 가능한 카메라 기기를 인식하지 못했습니다. 연결을 재확인해 주세요.": "No camera was found. Check the connection and try again.",
  "화면 우측 상단의": "At the top right of the screen,",
  "버튼을 눌러 모바일의 정식 브라우저(": "tap the button to open your mobile browser (",
  "버튼을 눌러 안드로이드 애플리케이션 정보 화면에서 카메라 권한을 직접": "tap the button to allow camera access in Android app info",
  "으로 활성화해 주셔야 합니다.": "to enable it.",
  "'허용'": "'Allow'",
  "'다시 묻지 않음' 등으로 권한 요청이 영구 차단된 경우, 아래": "If permission prompts have been permanently blocked, use the option below",
  ")에서 해당 웹사이트를 다시 실행하시면 즉시 정상 작동합니다!": ") and reopen the site.",
  "및": "and",
  "동작 중": "In progress",
  "보통": "Normal",
  "최대": "Maximum",
  // Additional help, examples and terms
  "AI 일정 알람 자동 예약": "Automatic AI schedule reminders",
  "Android / iOS 크로스 플랫폼 지원": "Works on Android and iOS",
  "Google Cloud 기기 간 완벽 백업 지원": "Backup across devices with Google Cloud",
  "Google Play 인앱 결제 시스템": "Google Play in-app billing",
  "Google Play의 환불 정책 및 절차": "Google Play's refund policies and procedures",
  "NEIS 네트워크 검색 중...": "Searching NEIS...",
  "✔️ 예약 완료": "✔️ Reminder scheduled",
  "개인정보 보호 최우선 설계 원칙:": "Privacy-first design:",
  "과목명과 상세 일정을 직접 기재해 주세요. 입력 완료 시 캘린더와 할 일 목록에 똑부러지게 등록됩니다.": "Enter the subject and details. They will be added to your calendar and task list.",
  "교과서 글자 분석, 오답노트 정리, 질문 해소를 위한 AI 핵심 클리닉 정리가 시작됩니다. 왼쪽 입력을 통해 시작해 보세요!": "Analyze textbook text, review mistakes and get answers with AI. Use the form to get started.",
  "기능은 사용자의 발표 자세, 시선 처리, 표정 및 목소리 성량을 실시간으로 분석하여 고품질의 채점 피드백을 전달합니다.": " analyzes posture, eye contact, facial expression and voice to provide feedback after practice.",
  "기준:": "Criteria:",
  "나의 수행평가 계획과 일정을 똑 소리나게 통합 스케줄링하세요": "Keep assignments and deadlines organized in one place.",
  "내가 작성하거나 AI가 생성해 준 대본들이 보관됩니다. 대본을 클릭하여 편집하거나 발표 연습에 활용할 수 있습니다.": "Your own and AI-generated scripts are saved here. Open one to edit or practice it.",
  "논리적인 서론-본론-결론 구조화 가동 중": "Structuring the introduction, body and conclusion...",
  "단축키 기능 연결": "Set up a shortcut",
  "똑똑하게 AI 발표 대본 작성 중...": "Writing your presentation script...",
  "똑똑하게 학습 시작": "Start studying",
  "매일 저녁 7시 내일의 스케줄 분석 및 피드백 제안.": "Review tomorrow's schedule at 7 PM each day.",
  "스마트 알림 흐름 예고 (전송 시점 기준)": "Planned reminder schedule",
  "수행평가 계획서를 등록하면 AI가 캘린더 자동 등록, 일정 생성 및 알림 예약을 수행합니다.": "Upload an assignment plan and AI will create calendar events and reminders.",
  "수행평가 계획표, 알림장, 칠판 판서 사진을 올리면 AI가 제목, 제출일, 준비물, 평가 기준 등을 자동 분석해 등록합니다.": "Upload an assignment sheet, notice or board photo to extract the title, due date, materials and grading criteria.",
  "시험 7일전, 5일전, 3일전, 1일전 푸시알림": "Notifications 7, 5, 3 and 1 day before an exam",
  "시험 일정으로 캘린더 등록": "Add exam to calendar",
  "시험 일정이 생기면 똑(Tok) AI가 아래 주기에 맞춰 자동 푸시 알람을 예고합니다.": "When you add an exam, TTOK schedules reminders at these intervals.",
  "시험 일주일 전, 5일 전, 3일 전, 하루 전 푸시 발송.": "Send reminders 7, 5, 3 and 1 day before the exam.",
  "얼굴을 잘 맞추고 아래 촬영 버튼을 눌러주세요!": "Frame your face and tap Capture below!",
  "완료 및 저장": "Finish and save",
  "정말로": "Are you sure you want to",
  "주제와 정보를 입력한 후 완료 버튼을 누르면, 발표에 꼭 어울리는 명품 대본과 팁이 마크다운 가이드와 함께 완성됩니다.": "Enter your topic and details to generate a presentation script and practical tips.",
  "플랫폼 모드": "Platform mode",
  "학년 수준과 청중 특성에 완벽히 들어맞는 스피치를 제조하고 있습니다...": "Tailoring the script to your grade and audience...",
  "🎉 1번 정답: 2번, 2번 정답: 3번, 3번 정답: 3번 입니다! 해설을 대조해 보세요.": "🎉 Answers: 1 → 2, 2 → 3, 3 → 3. Compare them with the explanations.",
  "📅 시험 3일 전 알람": "📅 Reminder 3 days before exam",
  "📅 시험 5일 전 알람": "📅 Reminder 5 days before exam",
  "📅 시험 일주일 전 알람": "📅 Reminder 1 week before exam",
  "📅 시험 하루 전 알람": "📅 Reminder 1 day before exam",
  "예: 1학기 기말고사, 3단원 단원평가": "e.g. First-semester final exam or Unit 3 test",
  "예: 3분, 5분 이내 (없으면 빈칸)": "e.g. 3 minutes or under 5 minutes (optional)",
  "예: 과학, 역사": "e.g. Science, History",
  "예: 교과서 3단원 삼각함수~지수함수 전체": "e.g. Textbook Unit 3: trigonometry through exponentials",
  "예: 구글 클래스룸 보고서 업로드 및 발표": "e.g. Upload a report to Google Classroom and present it",
  "예: 국어, 통합과학": "e.g. Korean, Integrated Science",
  "예: 기후 변화와 인류의 미래": "e.g. Climate change and the future of humanity",
  "예: 맞춤법 준수, 감정 묘사의 디테일, 인물 배치 등": "e.g. Spelling, emotional detail, character placement",
  "예: 색연필, 태블릿 PC": "e.g. Colored pencils, tablet",
  "예: 수소 결합이 왜 물의 끓는점을 높이나요?": "e.g. Why does hydrogen bonding raise water's boiling point?",
  "예: 역사, 통합과학": "e.g. History, Integrated Science",
  "예: 인류 문명의 진화와 기후 위기": "e.g. Civilization and the climate crisis",
  "예: 자유주제 소설 쓰기 및 발표": "e.g. Write and present a short story",
  "이 단축키 클릭 시 실행할 똑(TTOK)의 기능을 선택해 주세요. 이름과 아이콘은 기능에 맞춰 자동으로 설정됩니다.": "Choose what this shortcut opens. Its name and icon will be set automatically.",
  "스마트폰 [설정] &gt; [애플리케이션] &gt; [사용 중인 브라우저 앱] &gt; [권한]에서 카메라 권한이 '허용' 상태인지 꼭 확인해 주세요.": "In phone Settings > Apps > Your browser > Permissions, make sure Camera is allowed.",
  "상단 '발표 대본 작성' 탭에서 AI 대본을 먼저 생성하면, 이곳에 원터치 프롬프트 프롬프팅 용도로 자동 동기화됩니다.": "Generate an AI script in the Write script tab and it will appear here for practice.",
  "새 창에서 열기": "Open in a new window",
  "삼성 인터넷": "Samsung Internet",
  "똑(Tok) AI 발표 연습": "TTOK AI presentation practice",
  "똑": "TTOK",
  // Terms shown in the app. These are informational translations; Korean remains the source text.
  "본 약관은 \"똑(TTOK) 학생 수행평가 및 발표 대비 보조 플랫폼\"(이하 \"서비스\")의 이용에 관한 조건 및 절차, 이용자와 똑(TTOK) 서비스 개발자 간의 권리, 의무 및 제반 책임 사항을 명확히 규정함을 목적으로 합니다.": "These terms describe the conditions of use of TTOK, a student assignment and presentation support app, and the rights and responsibilities of users and the service provider.",
  "1. \"서비스\"란 학생의 수행평가 계획 자동화 스케줄링, 시험 카운트다운 관리, 교과 개념 분석, AI 스크립트 작성 및 발표 연습 녹화 후 분석 피드백(발음 딕션 점수, 시선 분석, 제스처 피드백)을 포함하여 앱에서 제공되는 학습 보조 기능을 총칭합니다.": "1. The service includes assignment scheduling, exam countdowns, subject analysis, AI script writing and post-recording presentation feedback.",
  "2. \"이용자\"란 서비스를 이용하기 위해 가입하고 학적 및 학습 목표를 설정하여 서비스를 활성화하는 학생, 학부모 및 교사를 말합니다.": "2. A user is a student, parent or teacher who signs up and uses the service.",
  "1. 똑(TTOK)은 이용자의 과도하고 불필요한 개인 식별 정보의 외부 노출 및 수집을 엄격히 제한하며, 입력받는 학교명, 학년, 반 등의 정보는 오직 맞춤화된 학습 캘린더 생성 및 편의 향상 목적으로만 보관됩니다.": "1. TTOK limits unnecessary collection or exposure of identifying information. School, grade and class information is used to personalize learning features.",
  "1. 이용자는 자신의 실제 학적 정보 및 공부 목표에 기반하여 일정을 올바르게 기재하고 수행할 권리를 가집니다.": "1. Users may manage their schedules based on their school information and learning goals.",
  "2. 이용자는 본 서비스 내의 기능(AI 사진 스캔 등록, AI 피드백 튜터, 발표 분석 등)을 타인의 지적재산권이나 초상권을 침해하지 않는 건전한 학업 및 자기계발적 범위 내에서만 정당하게 활용하여야 합니다.": "2. Users must use AI scanning, feedback and presentation tools for lawful study without infringing others' rights.",
  "3. 이용자는 다음 행위를 해서는 안 되며, 위반 시 회사는 사전 통지 없이 서비스 이용을 제한하거나 계정을 정지·해지할 수 있습니다: 서비스 운영을 방해하는 비정상적 대량 요청, 타인 계정 도용, 서비스 콘텐츠의 무단 복제·배포·상업적 이용, 역설계, 관계 법령 위반.": "3. Users must not disrupt the service, use another person's account, distribute or commercially exploit content without permission, reverse engineer the service, or break applicable law. Violations may lead to restrictions or termination.",
  "1. 똑(TTOK) 서비스에서 제공하는 모든 AI 분석 성적, 발음 교정 정보, 가중 점수 및 피드백 내용은 이용자의 학업적 참고와 프레젠테이션 스피치 향상을 돕기 위한 보조적 지표 자료일 뿐이며, 정확성·완전성을 보증하지 않습니다.": "1. AI scores, pronunciation analysis and feedback are learning aids and are not guaranteed to be accurate or complete.",
  "2. 해당 피드백 자료는 실제 학교 교사나 소속 교육기관의 지필고사 및 수행평가 실질 채점 기준과 다를 수 있으며, 본 서비스는 이용자가 기록한 정보의 완벽한 행정적·공식적 정확성이나 공인 평가 결과를 보증하지 않습니다. 이에 따른 학업 성과 및 채점 불일치 책임은 이용자 본인에게 있습니다.": "2. AI feedback may differ from a teacher's or school's assessment criteria. TTOK does not guarantee official grades or results.",
  "3. 서비스는 \"있는 그대로(AS-IS)\" 제공되며, 회사는 천재지변·정전·네트워크 장애·제3자 서비스 장애 등 합리적 통제를 벗어난 사유로 인한 서비스 중단에 책임을 지지 않습니다.": "3. The service is provided as-is. The provider is not responsible for interruptions outside its reasonable control, such as natural disasters or third-party outages.",
  "4. 법률이 허용하는 최대한의 범위에서, 서비스 이용으로 발생하는 간접·결과적·특별·징벌적 손해에 대해 회사는 책임을 지지 않으며, 손해배상 책임은 손해 발생일로부터 최근 3개월간 이용자가 실제 지불한 이용 요금 총액을 초과하지 않습니다. 무료 이용자의 경우 회사는 원칙적으로 손해배상 책임을 지지 않습니다.": "4. To the extent permitted by law, liability for indirect or consequential losses is limited. Any liability is capped at fees paid during the preceding three months.",
  "1. 똑(TTOK)은 무료로 제공되는 기본 서비스 외에, 유료 구독 상품인": "1. In addition to the free service, TTOK offers the paid subscription",
  "를 제공합니다. 똑 PRO 구독 시 월간 AI 기능 이용 횟수가 확대되며, AI 추천 리포트 등 PRO 전용 기능을 이용할 수 있습니다.": ", which increases the monthly AI allowance and enables PRO-only features such as AI study reports.",
  "2. 구독 상품 및 가격은 다음과 같습니다. (부가세 포함, Google Play 정책에 따라 변경될 수 있습니다)": "2. Subscription plans and prices are listed below (including tax; subject to Google Play changes).",
  "3. 결제는": "3. Payment is made through",
  "을 통해서만 이루어지며, 똑(TTOK)은 결제 정보를 직접 수집하거나 저장하지 않습니다.": "only. TTOK does not collect or store payment details directly.",
  "4. 구독은 별도로 해지하지 않는 한 각 결제 주기(월간/연간)가 끝날 때 자동으로 갱신되며, 자동 갱신 전 Google Play를 통해 이용자에게 사전 고지됩니다.": "4. Subscriptions renew automatically at the end of each monthly or yearly term unless canceled. Google Play provides renewal notices.",
  "5. 구독 해지는 앱 내 설정 화면의": "5. You can cancel your subscription using",
  "메뉴 또는 Google Play 스토어의 구독 관리 화면에서 언제든지 직접 진행할 수 있습니다. 해지 시에도 이미 결제된 기간 동안은 계속 PRO 혜택을 이용할 수 있습니다.": "in Settings or Google Play's subscription management page. PRO benefits remain available through the paid period.",
  "6. 결제 취소 및 환불은": "6. Cancellations and refunds follow",
  "를 따르며, 똑(TTOK)이 자체적으로 환불을 처리하지 않습니다. 환불 요청은 Google Play 고객센터를 통해 진행해 주시기 바랍니다.": ". TTOK does not process refunds directly; contact Google Play support for a refund request.",
  "7. 이용자의 약관 위반이나 부정 이용(비정상적 방법으로 무료 이용 한도를 우회하는 행위 등)이 확인되는 경우, 회사는 환불 없이 구독 혜택 제공을 중단할 수 있습니다.": "7. Subscription benefits may be stopped without a refund if a user breaches these terms or abuses the service, including bypassing free-use limits.",
  "1. 서비스에 포함된 소프트웨어, 디자인, 로고, AI 프롬프트 구성 등 일체의 저작물에 대한 지적재산권은 회사에 귀속됩니다.": "1. Intellectual property rights in the app's software, design, logo and AI prompts belong to the service provider.",
  "2. 이용자는 회사의 사전 서면 동의 없이 서비스 콘텐츠를 복제, 송신, 출판, 배포하거나 제3자에게 이용하게 할 수 없습니다.": "2. Users may not copy, publish or distribute service content to others without prior written permission.",
  "회사는 이용자가 본 약관 또는 관계 법령을 위반하거나 서비스의 정상적인 운영을 방해한 경우, 사전 통지 후(긴급한 경우 사후 통지) 해당 이용자의 서비스 이용을 제한하거나 계정을 해지할 수 있습니다.": "The provider may restrict or terminate accounts that violate these terms or law, with advance notice where practicable.",
  "회사는 관계 법령을 위배하지 않는 범위에서 본 약관을 개정할 수 있으며, 개정 시 적용일자 및 개정사유를 명시하여 서비스 내 공지를 통해 사전 공지합니다. 이용자가 개정 약관의 적용일 이후에도 서비스를 계속 이용하는 경우 개정 약관에 동의한 것으로 봅니다.": "The provider may amend these terms in accordance with law and will give advance notice of the effective date and reason. Continued use after the effective date indicates acceptance.",
  "본 약관의 해석 및 이용자와 똑(TTOK) 서비스 간의 분쟁이 발생할 경우 대한민국 관계 법령을 준거법으로 하며, 법이 정한 관할 법원을 통하여 원만하고 합리적인 해결을 도모합니다.": "These terms are governed by the laws of the Republic of Korea. Disputes will be resolved in the courts designated by applicable law.",
  "똑(TTOK) 서비스 내에 기록된 캘린더 일정, 대본 연습 로그, 공부 기록 데이터를 영구 초기화합니다.": "Permanently reset calendar events, presentation practice logs and study records stored in TTOK.",
  "• 발표 연습을 시작하면 카메라와 마이크를 이용해 녹화합니다. 연습 종료 시 해당 영상·음성이 똑 서버를 거쳐 Google Gemini로 전송되어 발표 점수와 피드백을 생성합니다.": "• Presentation practice uses your camera and microphone. When you finish, the recording is sent through the TTOK server to Google Gemini for scores and feedback.",
  "• 영상·음성 원본은 똑 서버의 파일 저장소에 보관하지 않습니다. 요청 처리가 끝나면 기기의 임시 녹화 데이터도 정리합니다.": "• TTOK does not keep the original recording in its server file storage. Temporary data on your device is cleared after the request.",
  "• AI 사진 분석에는 선택한 이미지가 분석 서버와 AI 제공업체에 전송될 수 있습니다.": "• Images you select for AI analysis may be sent to the analysis server and AI provider.",
  "• PDF 대본 저장은 기기에서 처리하며, 사용자가 공유를 선택한 경우에만 선택한 앱에 전달됩니다.": "• Script PDFs are created on your device and shared only when you choose a destination.",
  "• 일정, 프로필, 발표 결과 등 계정 동기화 데이터는 Firebase에 보관될 수 있습니다.": "• Synced account data such as schedules, profile and practice results may be stored in Firebase.",
  "• AI 제공업체의 데이터 처리 조건은 해당 업체의 정책에 따릅니다.": "• The AI provider processes data under its own policies.",
  "• 모든 통신은 HTTPS를 사용합니다.": "• All communication uses HTTPS.",
  "• 월간 구독: 2,900원 / 월": "• Monthly subscription: ₩2,900 per month",
  "• 연간 구독: 29,000원 / 년": "• Yearly subscription: ₩29,000 per year",
  // Messages, form options and generated UI suggestions
  "150회": "150 uses",
  "50회": "50 uses",
  "3단계: 프로필 불러오는 중": "Step 3: Loading profile",
  "AI 리포트를 생성하지 못했어요.": "Couldn't generate the AI report.",
  "AI 리포트를 생성하지 못했어요. 잠시 후 다시 시도해 주세요.": "Couldn't generate the AI report. Please try again later.",
  "Firestore 일일 읽기/쓰기 한도가 초과되었습니다. 내일 다시 이용 가능합니다.": "The daily Firestore limit has been reached. Please try again tomorrow.",
  "Google Play 결제 상품을 불러오지 못했어요. Play 스토어에서 테스트 참여와 설치 계정을 확인해 주세요.": "Couldn't load Google Play products. Check your testing access and the account used to install the app.",
  "PDF를 만들거나 공유하지 못했어요. 다시 시도해 주세요.": "Couldn't create or share the PDF. Please try again.",
  "공유하지 못했어요. 잠시 후 다시 시도하거나 대본 복사를 이용해 주세요.": "Couldn't share the script. Try again or copy the script instead.",
  "구매 내역을 복원했어요! 반영까지 몇 초 정도 걸릴 수 있어요.": "Purchases restored! Updates may take a few seconds.",
  "구매 처리 중 문제가 발생했어요. 잠시 후 다시 시도해 주세요.": "There was a problem with the purchase. Please try again shortly.",
  "구매가 완료됐어요! 반영까지 몇 초 정도 걸릴 수 있어요.": "Purchase complete! Updates may take a few seconds.",
  "복원 중 문제가 발생했어요. 잠시 후 다시 시도해 주세요.": "Couldn't restore purchases. Please try again shortly.",
  "복원할 구매 내역을 찾지 못했어요.": "No purchases to restore were found.",
  "현재 구매 가능한 상품이 없어요. 잠시 후 다시 시도해 주세요.": "No products are currently available. Please try again later.",
  "로그인 중 에러가 발생했습니다. 다시 시도해 주세요.": "Sign-in failed. Please try again.",
  "로그인 창이 닫혔습니다. 본인 인증을 완료하려면 다시 로그인해 주세요.": "The sign-in window closed. Try again to complete authentication.",
  "이전 로그인 요청이 취소되었습니다. 다시 시도해 주세요.": "The previous sign-in was canceled. Please try again.",
  "네트워크 연결이 불안정합니다. 인터넷 연결 상태를 확인 후 다시 시도해 주세요.": "The connection is unstable. Check your internet connection and try again.",
  "브라우저 팝업이 차단되었습니다. 팝업 차단을 해제한 뒤 다시 로그인해 주세요.": "The sign-in popup was blocked. Allow popups and try again.",
  "비활성화된 계정입니다. 관리자에게 문의해 주세요.": "This account has been disabled. Contact support.",
  "올바른 이메일 형식이 아닙니다.": "Enter a valid email address.",
  "이미 가입된 이메일입니다. 로그인을 시도해 주세요.": "This email is already registered. Try signing in.",
  "비밀번호는 6자 이상이어야 합니다.": "Your password must be at least 6 characters.",
  "이메일 또는 비밀번호가 올바르지 않습니다.": "Incorrect email or password.",
  "가입되지 않은 이메일입니다. 회원가입을 먼저 진행해 주세요.": "This email is not registered. Sign up first.",
  "너무 많은 시도가 감지되었습니다. 잠시 후 다시 시도해 주세요.": "Too many attempts. Please try again later.",
  "이메일과 비밀번호를 모두 입력해 주세요.": "Enter both your email and password.",
  "비밀번호를 재설정할 이메일을 먼저 입력해 주세요.": "Enter your email to reset your password.",
  "비밀번호 재설정 메일을 보냈습니다. 받은편지함을 확인해 주세요.": "Password reset email sent. Check your inbox.",
  "메일 전송에 실패했습니다. 잠시 후 다시 시도해 주세요.": "Couldn't send the email. Please try again later.",
  "아직 인증이 확인되지 않았습니다. 메일함을 확인해 주세요.": "Your email has not been verified yet. Check your inbox.",
  "인증 메일 다시 보내기": "Resend verification email",
  "인증 메일을 다시 보냈습니다.": "Verification email sent again.",
  "확인 중 오류가 발생했습니다. 다시 시도해 주세요.": "Verification failed. Please try again.",
  "공부 도우미 분석 도중 오류가 발생했습니다.": "An error occurred during study analysis.",
  "대본을 만들지 못했어요. 잠시 후 다시 시도해 주세요.": "Couldn't create the script. Please try again later.",
  "분석을 처리할 수 없습니다. AI 키와 네트워크를 점검해 주세요.": "Couldn't process the analysis. Check the AI service and your connection.",
  "이미지 분석 오류가 발생했습니다.": "Image analysis failed.",
  "이미지 파일을 변환하는 도중 에러가 발생했습니다.": "Couldn't convert the image file.",
  "급식 정보를 불러오지 못했습니다.": "Couldn't load school meals.",
  "학교 정보를 불러올 수 없습니다.": "Couldn't load school information.",
  "학교가 등록되어 있지 않습니다": "No school is registered",
  "학교 설정에서 학교를 등록해 주세요": "Add a school in School settings",
  "학교를 검색해 주세요": "Search for a school",
  "사진 촬영/스캔으로 자동 일정 등록": "Add an event from a photo or scan",
  "대본 보관함에 성공적으로 저장되었습니다!": "Script saved!",
  "정말로 이 대본을 삭제하시겠습니까?": "Delete this script?",
  "설정이 안전하게 적용되었습니다!": "Settings saved!",
  "똑(TTOK) 푸시 알림 설정이 안전하게 갱신되었습니다!": "TTOK notification settings updated!",
  "발표를 평가하려면 마이크 권한이 필요해요. 기기 설정에서 허용해 주세요.": "Microphone permission is required for presentation feedback. Allow it in your device settings.",
  "녹화 영상이 너무 커요. 4분 이내로 다시 연습해 주세요.": "The recording is too large. Practice for no more than four minutes.",
  "녹화 파일을 만들지 못했어요.": "Couldn't create the recording.",
  "녹화 파일을 읽지 못했어요.": "Couldn't read the recording.",
  "녹화를 시작하지 못했어요.": "Couldn't start recording.",
  "다시 분석할 녹화 자료가 없어요. 새로 연습해 주세요.": "There is no recording to retry. Please practice again.",
  "발표를 3초 이상 녹화한 뒤 분석해 주세요.": "Record at least three seconds before requesting feedback.",
  "분석 결과가 완성되지 않았어요. 다시 시도해 주세요.": "The analysis was incomplete. Please try again.",
  "분석을 완료하지 못했어요. 잠시 후 다시 시도해 주세요.": "Couldn't finish the analysis. Please try again later.",
  "이 기기에서는 영상 녹화가 지원되지 않아요.": "Video recording is not supported on this device.",
  "이 기기에서 AI 분석용 영상 형식을 녹화할 수 없어요.": "This device cannot record a video format supported by AI analysis.",
  "연습 화면이 닫혀 녹화를 시작하지 않았어요.": "The practice screen closed before recording began.",
  "카메라에 접근할 수 없습니다. 권한 설정을 확인해 주세요.": "Couldn't access the camera. Check its permissions.",
  "카메라가 다른 앱에서 이미 사용 중입니다. 백그라운드 앱을 종료해 주세요.": "Another app is using the camera. Close background apps and try again.",
  "카메라 접근 권한이 차단되었습니다. 휴대폰 설정에서 카메라 권한을 '허용'으로 변경한 후 다시 시도해 주세요.": "Camera access is blocked. Allow it in your phone settings and try again.",
  "카메라 접근 권한이 차단되었습니다. 브라우저 설정 또는 휴대폰 설정에서 카메라 권한을 '허용'으로 변경한 후 다시 시도해 주세요.": "Camera access is blocked. Allow it in your browser or phone settings and try again.",
  "카메라 장치가 감지되지 않거나, 모바일 인앱 브라우저/보안 환경 제한으로 인해 접근이 불가합니다. 모바일 기본 브라우저(Chrome/삼성 인터넷)로 접속하시거나 우측 상단 '새 창에서 열기' 버튼을 클릭해 주세요!": "No camera was detected, or your browser blocks access. Open the app in Chrome or Samsung Internet.",
  "소리 내어 말해보세요. 음성 자막이 이곳에 표시됩니다...": "Speak aloud. Live captions will appear here...",
  "음성 인식": "Speech recognition",
  "마이크": "Microphone",
  "허용": "Allow",
  "다시 묻지 않음": "Don't ask again",
  "전송 중...": "Sending...",
  "저장 완료": "Saved",
  "복사 완료": "Copied",
  "편집 완료": "Done editing",
  "뒤로": "Back",
  "서비스": "Service",
  "이용자": "User",
  "교과": "Subject",
  "기타": "Other",
  "기본 말투": "Default tone",
  "직접 작성": "Write your own",
  "대본 수정": "Edit script",
  "발표 연습": "Presentation practice",
  "발표지수": "Presentation score",
  "목소리": "Voice",
  "발음": "Pronunciation",
  "자세": "Posture",
  "손동작": "Gestures",
  "표정": "Expression",
  "시선": "Eye contact",
  "시간 미정": "No time set",
  "하루 종일": "All day",
  "학교": "School",
  "초등학교": "Elementary school",
  "고등학교": "High school",
  "청중": "Audience",
  "바름": "Correct",
  "밝음": "Bright",
  "안정적": "Steady",
  "적절함": "Appropriate",
  "요일": "Day of week",
  "월": "Mon",
  "화": "Tue",
  "수": "Wed",
  "목": "Thu",
  "금": "Fri",
  "토": "Sat",
  "일": "Sun",
  "공부 📚": "Study 📚",
  "수행평가 📝": "Assignment 📝",
  "숙제 🗂️": "Homework 🗂️",
  "시험 ✏️": "Exam ✏️",
  "지필 고사": "Written exam",
  "자료제출": "Submit materials",
  "직접제출": "Submit in person",
  "자유 발표 주제": "Free presentation topic",
  "직접 입력한 발표 주제": "Custom presentation topic",
  "친근한 말투": "Friendly tone",
  "친근하고 당당한 말투": "Friendly and confident tone",
  "지식 전달 및 청중 설득": "Inform and persuade the audience",
  "PPT를 활용한 프리젠테이션": "Presentation with slides",
  "반 친구들과 선생님": "Classmates and teacher",
  "등록된 과목별 스케줄과 기준 확인": "Review schedules and criteria by subject",
  "학습 기본 환경 설정": "Basic study settings",
  "학습 목표 설정 및 소속 학교 급식 연동": "Set study goals and link school meals",
  "내 정보 및 학교 조회": "My details and school",
  "새로운 학생": "New student",
  "학습한 텍스트 바탕 실전 AI 퀴즈 풀기": "Take an AI quiz on the text you studied",
  "교과 공부 AI 질문 & 요약": "Ask AI about subjects and get summaries",
  "수행평가 계획서 스캔": "Scan assignment plan",
  "수행평가 일정 목록": "Assignment list",
  "수행평가 일정 수동 등록": "Add assignment manually",
  "단축키 수정": "Edit shortcut",
  "다크 모드 제어 및 전체 데이터 초기화": "Control dark mode and reset data",
  "📚 광합성의 원리 및 명반응/암반응 핵심 요약": "📚 Photosynthesis: light and dark reactions",
  "🔍 삼각함수 주기 찾기 오답 집중 처방": "🔍 Review errors finding trigonometric periods",
  "프로필 미설정": "Profile not set",
  "올바르지 않은 요청 경로예요.": "Invalid request path.",
  "로그인 상태가 아닙니다.": "You are not signed in.",
  "Google 로그인에 실패했습니다. 다시 시도해 주세요.": "Google sign-in failed. Please try again.",
  "스쿨메이트": "Schoolmate",
  "1단계: 구글 계정 선택 중": "Step 1: Choosing a Google account",
  "2단계: Firebase 로그인 처리 중": "Step 2: Signing in with Firebase",
  "이 오류는 자동으로 재시도되지 않으며, 잠시 후(약 1~2분 후) 다시 분석/질문 버튼을 눌러 시도해 주세요.": "This won't retry automatically. Wait 1–2 minutes, then try the analysis or question again.",
  "이 오류는 자동으로 재시도되지 않으며, 잠시 후(약 1~2분 후) 다시 이미지를 등록하여 시도해 주세요.": "This won't retry automatically. Wait 1–2 minutes, then upload the image again.",
  "정상적인 JSON 응답이 아닙니다.": "The server returned an invalid response.",
  "정상적인 JSON 응답이 아닙니다. (HTML 수신)": "The server returned a web page instead of a valid response.",
  "서버 분석 실패. API 키나 파일 형식 확인이 필요합니다.": "Server analysis failed. Check the AI service and file format.",
  "텍스트를 입력하거나 분석할 교과서 사진을 등록해 주세요.": "Enter text or upload a textbook photo for analysis.",
  "상세 설명은 오답노트에서 확인하세요.": "See the mistake notebook for details.",
  "프로필 탭에서 이번 학기 최종 목표를 등록해 보세요!": "Set a goal for this semester in your profile.",
  "오늘 배운 내용 당일 복습하기": "Review today's lessons today",
  "하루 공부 계획 세우기": "Make a daily study plan",
  "하루 공부 계획 모두 실천하기": "Complete today's study plan",
  "하루 1개 이상 개념 완벽히 이해하기": "Master at least one concept each day",
  "하루 문제집 2페이지 이상 풀기": "Complete at least two workbook pages a day",
  "하루에 영어 단어 20개 외우기": "Learn 20 English words a day",
  "매일 30분 이상 공부하기": "Study for at least 30 minutes each day",
  "수업 시간 집중하기": "Stay focused in class",
  "수업 예습 또는 복습 매일 하기": "Preview or review lessons daily",
  "공부 시작 시간을 일정하게 유지하기": "Start studying at a consistent time",
  "쉬는 시간과 공부 시간을 규칙적으로 지키기": "Keep regular study and break times",
  "스마트폰 사용 시간 줄이기": "Reduce phone time",
  "부족한 과목 집중 보완하기": "Focus on weaker subjects",
  "모르는 문제 끝까지 해결하기": "Work through questions you don't understand",
  "수학 오답노트 꾸준히 작성하기": "Keep a math mistake notebook",
  "암기 과목 매일 복습하기": "Review memorization subjects daily",
  "시험 범위 미리미리 공부하기": "Study exam topics early",
  "시험 전까지 모든 과목 복습 완료하기": "Review every subject before the exam",
  "이번 학기 목표 성적 달성하기": "Reach your grade goal this semester",
  "일주일 동안 지각 없이 등교하기": "Get to school on time all week",
  "일주일에 오답노트 3회 작성하기": "Update the mistake notebook three times a week",
  "영어 지문 하루 1개 읽기": "Read one English passage a day",
  "국어 독서 하루 20분 하기": "Read Korean for 20 minutes a day",
  "독서 한 권 완독하기": "Finish reading a book",
  "수행평가 미루지 않고 제출하기": "Submit assignments on time",
  "학교 숙제 당일 완료하기": "Finish homework the same day",
  "집중해서 공부하는 습관 기르기": "Build focused study habits",
  "포기하지 않고 끝까지 공부하기": "Keep going until you finish",
  "필기 정리 깔끔하게 하기": "Organize class notes clearly",
  "오답노트에 수집된 취약 문항 복습 및 재검토": "Review difficult questions in your mistake notebook",
  "교과서 핵심 요약 2회 정독": "Read the textbook summary twice",
  "교과서 중단원, 대단원 확인 문제 전체 풀이": "Complete all unit review questions",
  "교과서 핵심 날개 단어 및 족보 단속": "Review key terms and past questions",
  "과목별 세부 시험 범위 및 학습 스케줄링": "Plan study sessions for each subject's exam topics",
  "교과 범위 요약 및 모르는 부분 질문하기": "Summarize exam topics and ask about unclear parts",
  "AI 핵심 요약": "AI key summary",
  "AI 실력 진단": "AI skill check",
  "AI 오답 노하우": "AI mistake review",
  "AI 일대일 상담": "One-on-one AI help",
  "AI 발표 대본 맞춤 작성": "Write a personalized AI presentation script",
  "AI 실시간 발표 실전 연습": "Practice a presentation with AI",
  "AI 문제생성기로 광범위 개념 검증 문제 2회 추가 풀이": "Do two more AI quizzes covering all key concepts",
  "AI 요약본과 필기 노트 1:1 대조 분석": "Compare AI summaries with your class notes",
  "개념 설명 직접 1분 스피치 해보기 (발표 연습 탭 이용)": "Give a one-minute explanation in Presentation practice",
  "틀린 문제 사진 등록하여 AI 오답 분석 처방전 확보": "Upload a missed question for AI feedback",
  "주요 공식 및 핵심 암기 단어 플래시 카드화": "Create flashcards for formulas and terms",
  "어려운 수학 공식/과학 메커니즘을 백지에 마인드맵으로 안 보고 그리기": "Draw a mind map of difficult formulas or concepts from memory",
  "제한 시간 45분 맞추어 실전 고사 시뮬레이션": "Simulate a 45-minute exam",
  "취약 개념 오답노트 단 1회 훑어보기": "Review weak concepts once more",
  "D-5 (개념 총정리)": "D-5 (Review core concepts)",
  "D-4 (단원 정밀 격파)": "D-4 (Review each unit)",
  "D-3 (실전 기출 체득)": "D-3 (Practice past papers)",
  "D-2 (취약점 철저 봉쇄)": "D-2 (Focus on weak spots)",
  "D-1 (마지막 최종 단속)": "D-1 (Final review)",
};
